[pgcli.main]
auto_expand = "True"
destructive_statements_require_transaction = "True"
generate_aliases = "True"
generate_casing_file = "True"
hide_named_query_text = "True"
keyring = "False"
multi_line = "True"
null_string = "NULL"
pager = "less -RXF"
prompt = "\\dsn_alias:\\u@\\d\\# "
row_limit = "500"
syntax_style = "monokai"
use_local_timezone = "False"