# ╔═══════════════════════════════════════════════╗
# ║  GENERATED BY CHEZMOI - DO NOT EDIT MANUALLY  ║
# ╚═══════════════════════════════════════════════╝

# Reset the terminal with escape sequences
autoload -Uz add-zsh-hook

function reset_broken_terminal () {
  printf '%b' '\e[0m\e(B\e)0\017\e[?5l\e7\e[0;0r\e8'
}

add-zsh-hook -Uz precmd reset_broken_terminal

# If can't execute the directory, perform the cd command to that
setopt AUTO_CD
